<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>br.net.lls</groupId>
  <artifactId>lls-app</artifactId>
  <version>1.0-SNAPSHOT</version>

  <name>lls-app</name>
  <url>https://github.com/lls-ws/lls-src</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
    <spring.version>7.0.3</spring.version>
  </properties>
  
  <dependencyManagement>
    <dependencies>
        <!-- spring-framework-bom -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-framework-bom</artifactId>
            <version>${spring.version}</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
	
	<!-- TEST -->
	
	<!-- junit -->
    <dependency>
		<groupId>junit</groupId>
		<artifactId>junit</artifactId>
		<version>4.11</version>
		<scope>test</scope>
    </dependency>
    
    <!-- PROVIDED -->
    <!-- Use scope "provided" if your container provides it (e.g., Tomcat/WildFly) -->
    
    <!-- javax.persistence-api | Migration to jakarta.persistence-api -->
    <dependency>
		<groupId>javax.persistence</groupId>
		<artifactId>javax.persistence-api</artifactId>
		<version>2.2</version>
		<scope>provided</scope>
	</dependency>
    
    <!-- javax.servlet-api | Migration to jakarta.servlet -->
    <dependency>
		<groupId>javax.servlet</groupId>
		<artifactId>javax.servlet-api</artifactId>
		<version>4.0.1</version>
		<scope>provided</scope>
	</dependency>
    
    <!-- COMPILE -->
    
    <!-- joda-time | Migration to java.time -->
    <dependency>
		<groupId>joda-time</groupId>
		<artifactId>joda-time</artifactId>
		<version>2.14.0</version>
		<scope>compile</scope>
	</dependency>
	
	<!-- jackson-core -->
	<dependency>
		<groupId>com.fasterxml.jackson.core</groupId>
		<artifactId>jackson-core</artifactId>
		<version>2.21.0</version>
		<scope>compile</scope>
	</dependency>
	
	<!-- jackson-databind -->
    <dependency>
		<groupId>com.fasterxml.jackson.core</groupId>
		<artifactId>jackson-databind</artifactId>
		<version>2.21.0</version>
		<scope>compile</scope>
	</dependency>
    
    <!-- javax.json-api | Migration to jakarta.json -->
    <dependency>
		<groupId>javax.json</groupId>
		<artifactId>javax.json-api</artifactId>
		<version>1.1.4</version>
		<scope>compile</scope>
	</dependency>

	<!-- validation-api | Migration to jakarta.validation -->
    <dependency>
		<groupId>javax.validation</groupId>
		<artifactId>validation-api</artifactId>
		<version>2.0.1.Final</version>
		<scope>compile</scope>
	</dependency>

    <!-- hibernate-core | Migration to org.hibernate.orm - hibernate-core -->
    <dependency>
		<groupId>org.hibernate</groupId>
		<artifactId>hibernate-core</artifactId>
		<version>7.3.0.CR1</version>
		<type>pom</type>
		<scope>compile</scope>
	</dependency>
    
    <!-- hibernate-validator -->
    <dependency>
		<groupId>org.hibernate.validator</groupId>
		<artifactId>hibernate-validator</artifactId>
		<version>9.1.0.Final</version>
		<scope>compile</scope>
	</dependency>
    
    <!-- json -->
    <dependency>
		<groupId>org.json</groupId>
		<artifactId>json</artifactId>
		<version>20251224</version>
		<scope>compile</scope>
	</dependency>
    
    <!-- spring-beans -->
    <dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-beans</artifactId>
	</dependency>
    
    <!-- spring-context -->
    <dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-context</artifactId>
	</dependency>
    
    <!-- spring-tx -->
    <dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-tx</artifactId>
	</dependency>
    
    <!-- spring-webmvc -->
    <dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-webmvc</artifactId>
	</dependency>
    
    <!-- spring-web -->
    <dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-web</artifactId>
	</dependency>
    
    <!-- spring-core -->
    <dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-core</artifactId>
	</dependency>
    
  </dependencies>

  <build>
    <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
      <plugins>
        <!-- clean lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#clean_Lifecycle -->
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        <!-- default lifecycle, jar packaging: see https://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
        <!-- site lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#site_Lifecycle -->
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
