<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>br.net.lls</groupId>
  <artifactId>lls-core</artifactId>
  <version>6.0.0</version>
  <!-- Semantic Versioning: 1.0.0 (MAJOR.MINOR.PATCH)
	MAJOR (1.x.x) - backward-incompatible changes
	MINOR (x.0.x) - new functionality added
	PATCH (x.x.0) - bug fixes
  -->

  <name>lls-core</name>
  <url>https://github.com/lls-ws/lls-src</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <spring.version>7.0.3</spring.version>
    <jasperreports.version>7.0.3</jasperreports.version>
  </properties>
  
  <dependencyManagement>
    
    <dependencies>
        
        <!-- spring-framework-bom -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-framework-bom</artifactId>
            <version>${spring.version}</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
        
    </dependencies>
    
  </dependencyManagement>

  <dependencies>
	
	<!-- TEST -->
	
	<!-- junit-jupiter-api -->
    <dependency>
		<groupId>org.junit.jupiter</groupId>
		<artifactId>junit-jupiter-api</artifactId>
		<version>6.0.2</version>
		<scope>test</scope>
	</dependency>
    
    <!-- PROVIDED -->
    <!-- Use scope "provided" if your container provides it (e.g., Tomcat/WildFly) -->
    
    <!-- jakarta.persistence-api -->
    <dependency>
		<groupId>jakarta.persistence</groupId>
		<artifactId>jakarta.persistence-api</artifactId>
		<version>3.2.0</version>
		<scope>compile</scope>
	</dependency>
    
    <!-- jakarta.servlet-api -->
    <dependency>
		<groupId>jakarta.servlet</groupId>
		<artifactId>jakarta.servlet-api</artifactId>
		<version>6.1.0</version>
		<scope>provided</scope>
	</dependency>
    
    <!-- COMPILE -->
    
    <!-- joda-time | Migration to java.time -->
    <dependency>
		<groupId>joda-time</groupId>
		<artifactId>joda-time</artifactId>
		<version>2.14.0</version>
		<scope>compile</scope>
	</dependency>
    
    <!-- json -->
    <dependency>
		<groupId>org.json</groupId>
		<artifactId>json</artifactId>
		<version>20251224</version>
		<scope>compile</scope>
	</dependency>
	
	<!-- jasperreports | 1 Vulnerability -->
	<dependency>
		<groupId>net.sf.jasperreports</groupId>
		<artifactId>jasperreports</artifactId>
		<version>${jasperreports.version}</version>
		<scope>compile</scope>
	</dependency>
	
	<!-- jasperreports-json -->
	<dependency>
		<groupId>net.sf.jasperreports</groupId>
		<artifactId>jasperreports-json</artifactId>
		<version>${jasperreports.version}</version>
		<scope>compile</scope>
	</dependency>
	
	<!-- JACKSON -->
	<!-- jackson-core -->
	<dependency>
		<groupId>com.fasterxml.jackson.core</groupId>
		<artifactId>jackson-core</artifactId>
		<version>2.21.0</version>
		<scope>compile</scope>
	</dependency>
	
	<!-- jackson-databind -->
    <dependency>
		<groupId>com.fasterxml.jackson.core</groupId>
		<artifactId>jackson-databind</artifactId>
		<version>2.21.0</version>
		<scope>compile</scope>
	</dependency>
    
    <!-- JAKARTA -->
    <!-- jakarta.mail-api -->
    <dependency>
		<groupId>jakarta.mail</groupId>
		<artifactId>jakarta.mail-api</artifactId>
		<version>2.1.5</version>
		<scope>compile</scope>
	</dependency>
	
    <!-- jakarta.json-api -->
    <dependency>
		<groupId>jakarta.json</groupId>
		<artifactId>jakarta.json-api</artifactId>
		<version>2.1.3</version>
		<scope>compile</scope>
	</dependency>
	
	<!-- jakarta.validation-api -->
    <dependency>
		<groupId>jakarta.validation</groupId>
		<artifactId>jakarta.validation-api</artifactId>
		<version>3.1.1</version>
		<scope>compile</scope>
	</dependency>
	
	<!-- HIBERNATE -->
	<!-- hibernate-validator -->
	<dependency>
		<groupId>org.hibernate.validator</groupId>
		<artifactId>hibernate-validator</artifactId>
		<version>9.1.0.Final</version>
		<scope>compile</scope>
	</dependency>
	
    <!-- hibernate-annotations | Migration to org.hibernate.orm » hibernate-core -->
    <!-- hibernate-core | Migration to org.hibernate.orm » hibernate-core -->
    <dependency>
		<groupId>org.hibernate</groupId>
		<artifactId>hibernate-core</artifactId>
		<version>5.6.15.Final</version>
		<scope>compile</scope>
	</dependency>
    
    <!-- COMMONS -->
    <!-- commons-io -->
	<dependency>
		<groupId>commons-io</groupId>
		<artifactId>commons-io</artifactId>
		<version>2.21.0</version>
		<scope>compile</scope>
	</dependency>
	
	<!-- commons-dbcp2 -->
	<dependency>
		<groupId>org.apache.commons</groupId>
		<artifactId>commons-dbcp2</artifactId>
		<version>2.14.0</version>
		<scope>compile</scope>
	</dependency>
	
    <!-- SPRING -->
    <!-- spring-beans -->
    <dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-beans</artifactId>
	</dependency>
    
    <!-- spring-context -->
    <dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-context</artifactId>
	</dependency>
    
    <!-- spring-tx -->
    <dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-tx</artifactId>
	</dependency>
    
    <!-- spring-webmvc -->
    <dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-webmvc</artifactId>
	</dependency>
    
    <!-- spring-web -->
    <dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-web</artifactId>
	</dependency>
    
    <!-- spring-core -->
    <dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-core</artifactId>
	</dependency>
    
  </dependencies>

  <build>
    <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
      <plugins>
        
        <!-- maven-clean-plugin -->
        <!-- clean lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#clean_Lifecycle -->
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.5.0</version>
        </plugin>
        
        <!-- maven-resources-plugin -->
        <!-- default lifecycle, jar packaging: see https://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.4.0</version>
        </plugin>
        
        <!-- maven-compiler-plugin -->
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.14.1</version>
          <configuration>
			<compilerArgs>
				<arg>-Xlint:deprecation</arg>
			</compilerArgs>
		  </configuration>
        </plugin>
        
        <!-- maven-surefire-plugin -->
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>3.5.4</version>
        </plugin>
        
        <!-- maven-jar-plugin -->
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.5.0</version>
        </plugin>
        
        <!-- maven-install-plugin -->
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>3.1.4</version>
        </plugin>
        
        <!-- maven-deploy-plugin -->
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>3.1.4</version>
        </plugin>
        
        <!-- maven-site-plugin -->
        <!-- site lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#site_Lifecycle -->
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.21.0</version>
        </plugin>
        
        <!-- maven-project-info-reports-plugin -->
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.9.0</version>
        </plugin>
        
        <!-- build-helper-maven-plugin -->
        <plugin>
			<groupId>org.codehaus.mojo</groupId>
			<artifactId>build-helper-maven-plugin</artifactId>
			<version>3.5.0</version>
			<executions>
				<execution>
					<id>add-js-source</id>
					<phase>generate-sources</phase>
					<goals>
						<goal>add-source</goal>
					</goals>
					<configuration>
						<sources>
							<source>src/main/javascript</source>
						</sources>
					</configuration>
				</execution>
			</executions>
		</plugin>
        
      </plugins>
    </pluginManagement>
  
  </build>

</project>
