jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://localhost/bd_lls?zeroDateTimeBehavior=convertToNull
jdbc.username=root
jdbc.password=mypassword
mail.host=smtp.gmail.com
mail.port=587
mail.encoding=ISO-8859-1
mail.username=lls.homeoffice@gmail.com
mail.password=mypassword
